name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: podman build -t app .
      - name: Run container
        run: |
          podman stop user-crud-app || true
          podman rm user-crud-app || true
          podman run -d --name user-crud-app -p 60080:60080 --restart always app
